# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1madM4JRIBOUfIgY-7HspmdNlBnXRU2y1
"""

def arearectangulo (a,b):
  operacion =(a+b)
  return operacion
  a=int(input())
  b=int(input())
  print("es el area del rectangulo",arearectangulo(a,b))