# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R9zrvGLDN1APogWKCqwnKvIQ5yrfeWQ9
"""

def suma (a,b):
  operacion = (a+b)
  return operacion
a=int(input())
b=int(input())
print("la suma es:",suma(a,b))