# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QWMZe5SO5SpzVe-vjEeWCRoEILC-Ia66
"""

radio = float(input("Ingresa el radio de la circunferencia: "))
perimetro = 2 * 3.1416 * radio
print("El perímetro de la circunferencia es:", perimetro)